# Generated by Django 4.1 on 2023-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='searches_left',
            field=models.IntegerField(default=5),
        ),
    ]
