# Generated by Django 4.1 on 2023-08-10 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
