# Generated by Django 4.1 on 2023-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_charterhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_type',
            field=models.CharField(choices=[('broker', 'Broker'), ('aircraft_operator', 'Aircraft Operator')], default='broker', max_length=255),
        ),
    ]
