# Generated by Django 4.1 on 2023-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_company_name_user_name_user_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='searches_left',
            field=models.IntegerField(default=3),
        ),
    ]
