# Generated by Django 4.1 on 2023-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_searches_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='searches_left',
            field=models.IntegerField(default=3),
        ),
    ]
