# Generated by Django 4.1 on 2023-09-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usersession_searches_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_searches',
            field=models.IntegerField(default=3),
        ),
    ]
