# Generated by Django 4.1 on 2023-10-14 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_max_searches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(choices=[('general', 'General'), ('military', 'Military'), ('dangerous', 'Dangerous'), ('livestock', 'Livestock'), ('perishable', 'Perishable')], max_length=255)),
                ('departure_airport', models.CharField(max_length=255)),
                ('arrival_airport', models.CharField(max_length=255)),
                ('departure_date', models.DateTimeField()),
                ('payload', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('date_flexibility_days', models.IntegerField(default=0)),
                ('location_flexibility_km', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('strong_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_dimension', models.IntegerField(default=0)),
                ('y_dimension', models.IntegerField(default=0)),
                ('z_dimension', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auction')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_type', models.CharField(choices=[('generated', 'Generated'), ('confirmed', 'Confirmed')], max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('aircraft', models.CharField(max_length=255)),
                ('flight_duration', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('price_currency', models.CharField(max_length=3)),
                ('operator_email', models.CharField(max_length=255)),
                ('operator_phone', models.CharField(max_length=255)),
                ('operator_note', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auction')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
